# Generated by Django 5.0.4 on 2024-06-10 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profesor'),
        ),
        migrations.AddField(
            model_name='project',
            name='theme',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
