# Generated by Django 5.0.4 on 2024-06-10 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_project_profesor_project_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='name',
            field=models.CharField(default='Profesor', max_length=100),
        ),
    ]
