# Generated by Django 5.0.4 on 2024-06-10 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profesor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='theme',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='estudiante',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.estudiante'),
        ),
    ]
