# Generated by Django 5.0.4 on 2024-06-10 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_estudiante_alter_project_theme_project_estudiante'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
